- name: Check for the carcinogenesis directory
  stat:
    path: "{{ target_dir }}/datasets/carcinogenesis"
  register: dataset_dir

- block:
  - name: Create dataset directory 
    file:
      path: "{{ target_dir }}/datasets/carcinogenesis/"
      state: directory

  - name: Create a temporary download directory
    tempfile:
      state: directory
      suffix: carcinogenesis
    register: tempdir

  - name: Download Carcinogenesis data
    get_url:
      url: https://files.dice-research.org/projects/tentris-alc2sparql/carcinogenesis.zip
      dest: "{{ tempdir.path }}/carcinogenesis.zip"

  - name: Unzip dataset and queries
    unarchive:
      remote_src: yes
      src: "{{ tempdir.path }}/carcinogenesis.zip"
      dest: "{{ target_dir }}/datasets/carcinogenesis/"
  when: not dataset_dir.stat.exists
